services:

  sume-frontend:
    container_name: sume-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    command: ["npm", "run", "start"]
    networks:
      - ai-advisor-networks
    
  
  sume-backend:
    container_name: sume-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    networks:
      - ai-advisor-networks

networks:
  ai-advisor-networks:
    driver: bridge
    name: ai-advisor-networks
